### ISSUE TITLE
P3 Post-hackathon Refactoring

### ISSUE THREAD

**Issue by khughitt** [NCBI-Hackathons/Pharmacogenomics_Prediction_Pipeline_P3#9]
This issue will help to organize some early refactoring efforts.
- [ ] Abstract pipeline to config/snakemake #4, #8 (@daler)
- [ ] high-level architecture #7 
- [ ] Merge `tools/` and `src/` scripts; normalize filenames #3 
- [ ] Normalize input and intermediate data source formats #2 (@ammhub)

**Comment by khughitt** [comment]
While we are on the topic of refactoring, do we plan to continue used a mix of R and Python for the intermediate scripts? Although my initial thoughts are to keep things in a single language for consistency, maintainability, and portability, using both languages would provide some flexibility in choosing the best language for a given task and allow people to contribute in whichever language they feel comfortable with. As long as the list doesn't start to grow to include scripts in ten other languages, I'd be fine with either approach.

**Comment by daler** [comment]
A typical RNA-seq pipeline uses code written in various languages, but the thing that makes them usable together is that they all have a command line interface.

I think having all scripts conform to these [ten recommendations](http://www.gigasciencejournal.com/content/2/1/15) should keep things usable while allowing everyone to work in their preferred language.

**Comment by khughitt** [comment]
Sounds good to me. Perhaps we can just create a dev guide somewhere where we describe things like coding standards for each language used.

**Comment by khughitt** [comment]
Regarding the docs, it looks like you have started some `.rst` files for various pipeline components.

What do you think about moving those files to `doc/src` and linking them together in an `index.rst`?

The architecture diagrams, etc. currently in doc/ could be moved to doc/extra.

**Comment by daler** [comment]
Sure. I meant to bring that up but forgot: should docs live on the github wiki or in text files in the repo?

If the latter, I'm a big fan of [sphinx](http://sphinx-doc.org/) for docs and I can get that set up.

**Comment by khughitt** [comment]
My preference is for repo docs. I'm not a huge fan of Github wiki pages.. I usually don't ever notice them when they exist and have trouble navigating them even when I look for them. 

I was also thinking Sphinx + [readthedocs](https://readthedocs.org/) would be a good way to go. That way we can have the docs regenerate on each commit.
